import type { SpatialNode } from "./types";

export const FIXTURE_NODES: SpatialNode[] = [
  {
    id: "motors",
    kind: "component",
    title: "motors",
    declaredName: "4× 2306 2400KV",
    x: 40,
    y: 80,
    width: 280,
    height: 200,
    fields: [
      { label: "count", value: "4" },
      { label: "KV", value: "2400" },
      { label: "SKU", value: "(fixture)" },
    ],
  },
  {
    id: "propellers",
    kind: "component",
    title: "propellers",
    declaredName: "HQ 5045 BN",
    x: 40,
    y: 310,
    width: 280,
    height: 200,
    fields: [
      { label: "geometry", value: "5 × 4.5 in" },
      { label: "SKU", value: "hq_5045_bn" },
    ],
  },
  {
    id: "esc",
    kind: "slot",
    title: "esc",
    declaredName: "",
    x: 40,
    y: 540,
    width: 280,
    height: 160,
    fields: [{ label: "estado", value: "no declarado (slot)" }],
  },
  {
    id: "battery",
    kind: "component",
    title: "battery",
    declaredName: "LiPo 6S 5000mAh",
    x: 360,
    y: 80,
    width: 280,
    height: 200,
    fields: [
      { label: "Wh", value: "100" },
      { label: "S", value: "6" },
    ],
  },
  {
    id: "frame",
    kind: "component",
    title: "frame",
    declaredName: "TBS Source One V5",
    x: 680,
    y: 80,
    width: 280,
    height: 180,
    fields: [
      { label: "wheelbase", value: "226 mm" },
      { label: "class", value: "5 in" },
    ],
  },
  {
    id: "frame_arm",
    kind: "part",
    title: "frame_arm",
    declaredName: "brazos",
    x: 680,
    y: 290,
    width: 280,
    height: 160,
    fields: [
      { label: "count", value: "4" },
      { label: "thickness", value: "6 mm" },
    ],
  },
  {
    id: "frame_plate",
    kind: "part",
    title: "frame_plate",
    declaredName: "placas",
    x: 680,
    y: 480,
    width: 280,
    height: 140,
    fields: [{ label: "material", value: "fibra de carbono" }],
  },
  {
    id: "flight_controller",
    kind: "component",
    title: "flight_controller",
    declaredName: "Pixhawk 4",
    x: 1000,
    y: 80,
    width: 280,
    height: 180,
    fields: [{ label: "model", value: "(fixture)" }],
  },
];
