from __future__ import annotations

from typing import Any
from typing import Protocol

from jarvis.config import PROMPT_VERSION
from jarvis.llm.prompt_builder import PromptBuilder
from jarvis.llm.response_parser import LLMResponseParser
from jarvis.llm.semantic_intent_adapter import AdaptRejection, SemanticIntentAdapter, SemanticInterpretation
from jarvis.schemas.state_schema import RuntimeState
from jarvis.utils.logger import StructuredLogger

_semantic_adapter = SemanticIntentAdapter()


class LLMClient(Protocol):
    def complete(self, messages: list[dict[str, str]], json_mode: bool = True) -> str:
        """Return a raw JSON string generated by the model."""


class JarvisLLMInterface:
    def __init__(
        self,
        client: LLMClient,
        prompt_builder: PromptBuilder | None = None,
        response_parser: LLMResponseParser | None = None,
        logger: StructuredLogger | None = None,
    ) -> None:
        self.client = client
        self.prompt_builder = prompt_builder or PromptBuilder()
        self.response_parser = response_parser or LLMResponseParser()
        self.logger = logger or StructuredLogger()

    def interpret(self, user_input: str, runtime_state: RuntimeState) -> dict:
        messages = self.prompt_builder.build_messages(user_input, runtime_state)
        raw_response = None
        try:
            raw_response = self.client.complete(messages, json_mode=True)
            llm_request = self.response_parser.parse(raw_response)
            validated = self.response_parser.validate_for_runtime(llm_request, runtime_state)
            action_request = self.response_parser.to_action_request(validated)
            semantic_trace = self._build_semantic_trace(action_request)
            self.logger.log_llm_event(
                {
                    "prompt_version": PROMPT_VERSION,
                    "user_input": user_input,
                    "messages": messages,
                    "llm_raw_output": raw_response,
                    "parsed_output": action_request,
                    "semantic_trace": semantic_trace,
                    "error": None,
                }
            )
            return action_request
        except Exception as error:
            self.logger.log_llm_event(
                {
                    "prompt_version": PROMPT_VERSION,
                    "user_input": user_input,
                    "messages": messages,
                    "llm_raw_output": raw_response,
                    "parsed_output": None,
                    "semantic_trace": None,
                    "error": str(error),
                }
            )
            return {
                "action": "simulate",
                "parameters": {
                    "error": "invalid_llm_output",
                    "message": "No se pudo interpretar la intención",
                },
                "raw_user_input": None,
            }

    def analyze(
        self,
        user_input: str,
        context: dict[str, Any],
        analyze_type: str = "explanation",
        reasoning_output: dict[str, Any] | None = None,
        conversation_history: list | None = None,
        goal_context: str | None = None,
    ) -> str:
        messages = self.prompt_builder.build_analysis_messages(
            user_input=user_input,
            context=context,
            analyze_type=analyze_type,
            reasoning_output=reasoning_output,
            conversation_history=conversation_history,
            goal_context=goal_context,
        )
        raw_response = None
        try:
            raw_response = self.client.complete(messages, json_mode=False)
            response_text = raw_response.strip()
            if not response_text:
                raise RuntimeError("Respuesta vacía para analyze")
            self.logger.log_llm_event(
                {
                    "prompt_version": PROMPT_VERSION,
                    "mode": "analyze",
                    "analyze_type": analyze_type,
                    "user_input": user_input,
                    "messages": messages,
                    "llm_raw_output": raw_response,
                    "parsed_output": {"message": response_text},
                    "error": None,
                }
            )
            return response_text
        except Exception as error:
            self.logger.log_llm_event(
                {
                    "prompt_version": PROMPT_VERSION,
                    "mode": "analyze",
                    "analyze_type": analyze_type,
                    "user_input": user_input,
                    "messages": messages,
                    "llm_raw_output": raw_response,
                    "parsed_output": None,
                    "error": str(error),
                }
            )
            return (
                "No puedo estimar ese impacto con precisión en este momento. "
                "Puedo explicar el comportamiento cualitativo con el contexto disponible si reformulas la pregunta."
            )

    @staticmethod
    def _build_semantic_trace(action_request: dict) -> dict | None:
        """Return a compact trace dict for iterate actions, None otherwise.

        Logged alongside each LLM event so that analysis of real inputs is
        possible without additional instrumentation:
          - variable   : canonical key resolved by the adapter (or raw if rejected)
          - confidence : self-reported by the LLM
          - routing    : "preseed_step2" | "fallback_wizard" | "rejected_derived" | "rejected_unknown" | "n/a"
        """
        if action_request.get("action") != "iterate":
            return None
        result = _semantic_adapter.adapt(action_request)
        if isinstance(result, SemanticInterpretation):
            return {
                "variable": result.variable,
                "confidence": result.confidence,
                "routing": "preseed_step2" if result.is_high_confidence else "fallback_wizard",
            }
        if isinstance(result, AdaptRejection):
            return {
                "variable": action_request.get("parameters", {}).get("variable"),
                "confidence": action_request.get("parameters", {}).get("confidence"),
                "routing": f"rejected_{result.reason}",
            }
        return {"variable": None, "confidence": None, "routing": "n/a"}
